In [2]:
import torch

In [14]:
# Ex.2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(0)
a = torch.randn(7,7, requires_grad = True, device = device)
a

tensor([[-0.9247, -0.4253, -2.6438,  0.1452, -0.1209, -0.5797, -0.6229],
        [-0.3284, -1.0745, -0.3631, -1.6711,  2.2655,  0.3117, -0.1842],
        [ 1.2866,  1.1820, -0.1271,  1.2169,  1.4353,  1.0605, -0.4941],
        [-1.4244, -0.7244, -1.2973,  0.0697, -0.0074,  1.8969,  0.6878],
        [-0.0779, -0.8373,  1.3506, -0.2879, -0.5965, -0.3283, -0.9086],
        [-0.8059, -0.7407, -0.0504,  0.5435,  1.5150,  0.0141,  0.4532],
        [ 1.6349,  0.7124, -0.1806,  1.0252, -1.4622, -0.7554, -0.1836]],
       device='cuda:0', requires_grad=True)

In [15]:
a.device

device(type='cuda', index=0)

In [16]:
torch.manual_seed(0)
b = torch.rand(1,7, requires_grad = False, device = device)
b

tensor([[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967, 0.4150]],
       device='cuda:0')

In [17]:
#Ex.3
c = a@(b.T)
c

tensor([[-1.3529],
        [ 0.0485],
        [ 4.2624],
        [ 0.8803],
        [-1.9036],
        [ 1.4377],
        [-0.0813]], device='cuda:0', grad_fn=<MmBackward0>)

In [18]:
# Ex.5
torch.cuda.manual_seed(1234)
a = torch.randn(7,7, requires_grad = True, device = device)
b = torch.rand(1,7, requires_grad = False, device = device)
c = a@(b.T)
c

tensor([[-2.3453],
        [ 0.0513],
        [ 1.7978],
        [-0.2752],
        [-1.1477],
        [ 1.2013],
        [ 2.5987]], device='cuda:0', grad_fn=<MmBackward0>)

In [21]:
# Ex.6
torch.manual_seed(1234)
a = torch.randn(2,3, device = 'cpu')
b = torch.randn(2,3, device = 'cpu')
a.to('cuda')
b.to('cuda')

tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')

In [22]:
print(a)
print(b)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])


In [26]:
# Ex.7
b2 = b.clone().detach().view(3,2)
b2

tensor([[ 0.2310,  0.6931],
        [-0.2669,  2.1785],
        [ 0.1021, -0.2590]])

In [25]:
c = a@b2
c

tensor([[-0.2000,  1.1706],
        [ 0.2649, -1.3140]])

In [27]:
# Ex.8
min = torch.min(c)
min

tensor(-1.3140)

In [28]:
max = torch.max(c)
max

tensor(1.1706)

In [29]:
#Ex.9
imax = torch.argmax(c)
imin  = torch.argmin(c)
print(imax, imin)

tensor(1) tensor(3)


In [31]:
max_index_ndim = torch.unravel_index(torch.argmin(c), c.shape)
print(max_index_ndim)

(tensor(1), tensor(1))


In [33]:
#Ex.10
torch.manual_seed(42)
a = torch.randn(1,1,1,10, device = 'cpu')
a

tensor([[[[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082,
           -0.6380,  0.4617,  0.2674]]]])

In [40]:
a.size()

torch.Size([1, 1, 1, 10])

In [42]:
c = [a[0, 0, 0, i] for i in range(10)]
c

[tensor(0.3367),
 tensor(0.1288),
 tensor(0.2345),
 tensor(0.2303),
 tensor(-1.1229),
 tensor(-0.1863),
 tensor(2.2082),
 tensor(-0.6380),
 tensor(0.4617),
 tensor(0.2674)]

In [36]:
result = [t.item() for t in c]
result

[0.33669036626815796,
 0.12880940735340118,
 0.23446236550807953,
 0.23033303022384644,
 -1.1228563785552979,
 -0.18632829189300537,
 2.2082014083862305,
 -0.637997031211853,
 0.46165722608566284,
 0.2673508822917938]

In [39]:
len(result)

10